[package]
name = "flow-example"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
dsl-kit      = { workspace = true }
dsl-kit-flow = { workspace = true }
miette       = { version = "7", features = ["fancy"] }
tokio        = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
futures      = "0.3"
